/**
 * FORGE Repository Bootstrap
 * Version: 1.0
 *
 * Usage:
 *   node bootstrap.js
 *
 * Safe to run multiple times.
 */

const fs = require("fs");
const path = require("path");

const ROOT = process.cwd();

function mkdir(dir) {
  const full = path.join(ROOT, dir);
  if (!fs.existsSync(full)) {
    fs.mkdirSync(full, { recursive: true });
    console.log(`📁 ${dir}`);
  }
}

function file(filePath, content = "") {
  const full = path.join(ROOT, filePath);

  mkdir(path.dirname(filePath));

  if (!fs.existsSync(full)) {
    fs.writeFileSync(full, content);
    console.log(`📄 ${filePath}`);
  }
}

function packageJson(name) {
  return JSON.stringify(
    {
      name,
      version: "0.0.1",
      private: true,
      main: "index.ts",
    },
    null,
    2
  );
}

function readme(title) {
  return `# ${title}

Generated by FORGE Bootstrap.

`;
}

function tsconfig() {
  return JSON.stringify(
    {
      extends: "../../tsconfig.base.json",
      compilerOptions: {
        outDir: "dist",
      },
      include: ["src"],
    },
    null,
    2
  );
}

const directories = [
  "apps/api",
  "apps/dashboard",
  "apps/worker",

  "packages/core",
  "packages/config",
  "packages/shared",
  "packages/database",
  "packages/events",
  "packages/types",
  "packages/ui",

  "collectors/reddit",
  "collectors/github",
  "collectors/hackernews",
  "collectors/rss",
  "collectors/producthunt",
  "collectors/youtube",
  "collectors/jobs",

  "engines/discovery",
  "engines/trend",
  "engines/pain",
  "engines/market",
  "engines/competition",
  "engines/feasibility",
  "engines/monetization",
  "engines/scoring",
  "engines/portfolio",

  "storage/repositories",
  "storage/migrations",
  "storage/snapshots",
  "storage/backups",

  "automation",

  "tests/e2e",
  "tests/integration",
  "tests/regression",
  "tests/performance",
  "tests/fixtures",

  "scripts",

  "infrastructure/docker",
  "infrastructure/ci",
  "infrastructure/deployment",
  "infrastructure/security",
  "infrastructure/monitoring",

  "docs/architecture",
  "docs/specifications",
  "docs/api",
  "docs/roadmap",
  "docs/adr",
  "docs/diagrams",
  "docs/research",
  "docs/engines",
];

directories.forEach(mkdir);

const packages = [
  "core",
  "config",
  "shared",
  "database",
  "events",
  "types",
  "ui",
];

packages.forEach((pkg) => {
  mkdir(`packages/${pkg}/src`);

  file(`packages/${pkg}/README.md`, readme(pkg));

  file(`packages/${pkg}/package.json`, packageJson(`@forge/${pkg}`));

  file(`packages/${pkg}/tsconfig.json`, tsconfig());

  file(
    `packages/${pkg}/src/index.ts`,
    `// ${pkg} package\nexport {};\n`
  );
});

const apps = ["api", "dashboard", "worker"];

apps.forEach((app) => {
  mkdir(`apps/${app}/src`);

  file(`apps/${app}/README.md`, readme(app));

  file(`apps/${app}/package.json`, packageJson(`@forge/${app}`));

  file(`apps/${app}/tsconfig.json`, tsconfig());

  file(
    `apps/${app}/src/index.ts`,
    `// ${app} application\nexport {};\n`
  );
});

const collectors = [
  "reddit",
  "github",
  "hackernews",
  "rss",
  "producthunt",
  "youtube",
  "jobs",
];

collectors.forEach((collector) => {
  [
    "application",
    "domain",
    "infrastructure",
    "interfaces",
    "tests",
  ].forEach((folder) =>
    mkdir(`collectors/${collector}/${folder}`)
  );

  file(
    `collectors/${collector}/README.md`,
    readme(`${collector} Collector`)
  );

  file(
    `collectors/${collector}/index.ts`,
    `// ${collector} collector\nexport {};\n`
  );
});

const engines = [
  "discovery",
  "trend",
  "pain",
  "market",
  "competition",
  "feasibility",
  "monetization",
  "scoring",
  "portfolio",
];

engines.forEach((engine) => {
  [
    "application",
    "domain",
    "infrastructure",
    "interfaces",
    "tests",
  ].forEach((folder) =>
    mkdir(`engines/${engine}/${folder}`)
  );

  file(
    `engines/${engine}/README.md`,
    readme(`${engine} Engine`)
  );

  file(
    `engines/${engine}/index.ts`,
    `// ${engine} engine\nexport {};\n`
  );
});

[
  ".gitignore",
  ".editorconfig",
  ".prettierrc",
  ".eslintrc.cjs",
  "tsconfig.base.json",
  "turbo.json",
].forEach((f) => file(f));

console.log("\n======================================");
console.log("✅ FORGE repository bootstrapped.");
console.log("======================================");
console.log("Next step: verify the generated folders in VS Code.");